import type { Metadata } from "next"
import "./globals.css"
import { Inter } from 'next/font/google'
import { Header } from "@/components/Header"

export const metadata: Metadata = {
  title: "Vivo Detecta",
  description: "Generated by create next app",
}

const inter = Inter({
    subsets: ['latin']
})

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="pt-br" suppressHydrationWarning>
        <body className={`${inter.className}`}>
            {children}
        </body>
    </html>
  )
}
